server:
  port: 8091

spring:
  application:
    name: microservice1
  data:
    mongodb:
      uri:  mongodb://localhost:27017/product

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
  instance:
      hostname: localhost  
    